//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdobeSymposium.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adobesymposiumdbEntities : DbContext
    {
        public adobesymposiumdbEntities()
            : base("name=adobesymposiumdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblIndustry> tblIndustries1 { get; set; }
        public DbSet<tblRegistration> tblRegistrations1 { get; set; }
        public DbSet<tblRole> tblRoles1 { get; set; }
    }
}
