//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdobeSymposium.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistration
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public int Industry { get; set; }
        public string Role { get; set; }
        public string ProfilePicture { get; set; }
        public string LinkedIn { get; set; }
        public string Twitter { get; set; }
        public string GPlus { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Password { get; set; }
    }
}
